server:
  port: 8080
  #单机模式经常会因为环境问题使Eureka进入自我保护模式，因此我们先关闭Eureka的自我保护功能并配置Eureka Server清理无效节点的时间间隔
  #在application.properties中增加配置
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 4000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoxiao?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: xiaoxiao
    username: root
    password: root
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #注册实例配置
  application:
    name: user-server
#eureka注册中心
eureka:
  #展示ip地址
  instance:
    prefer-ip-address: true
  #eureka注册地址
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/