#配置端口号
server:
  port: 81
  #单机模式经常会因为环境问题使Eureka进入自我保护模式，因此我们先关闭Eureka的自我保护功能并配置Eureka Server清理无效节点的时间间隔
  #在application.properties中增加配置
  enable-self-preservation: false
  eviction-interval-timer-in-ms: 4000
#服务提供者地址
#user:
#  userServicePath: http://localhost:8080/user/getUserInfoById/

spring:
  #注册实例配置
  application:
    name: user-client

#eureka注册中心
eureka:
  #展示ip地址
  instance:
    prefer-ip-address: true
  #eureka注册地址
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
#开启fegin
feign:
  hystrix:
    enabled: true
#断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试,缺省为1000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: false